### ISSUE TITLE
Have a discussion on whether to create a dataset for series too.

### ISSUE THREAD

**Issue by m-eren-erdogan** [course-dprep/team-project-team_8#10]
__Description__

Are we going to compare the movies with series? We have to decide if this will take too much time and effort. 

__Deliverables__

If decided on, an issue for creating the series dataset.

**Comment by m-eren-erdogan** [comment]
## We will just sample the movies and series and work on prototypes.

**Comment by KayvanderLinden1** [comment]
Movies vs. Tv Series will be used as a moderator in our research. Therefore, we can close this issue
