### ISSUE TITLE
*Housekeep* the Project

### ISSUE THREAD

**Issue by m-eren-erdogan** [course-dprep/team-project-team_8#27]
__Description__

Just remove the unnecessary issues, branches and update the dashboard!

__Deliverables__

A clean project interface.

**Comment by KayvanderLinden1** [comment]
I have removed branches that for now hold no extra value and/or have already been merged with the master repository. Furthermore, I have commented on and officially closed all issues that we have completed in the past. 

Finally, I will create an issue for Floris such that he can close his own issues and branches, as I have no clear idea of whether his issues and branches can or cannot be edited.
