### ISSUE TITLE
Add update log (in ReadMe)

### ISSUE THREAD

**Issue by ThomasGadellaa** [course-dprep/team-project-team_8#5]
In the self-study material they recommend to add when the last update was (see image). Maybe we can also include a short update log of what is/was done on which date.

<img width="833" alt="image" src="https://github.com/course-dprep/team-project-team_8/assets/144058724/c8aa3312-6280-45e7-ae6e-6ccaab9345a7">

**Comment by KayvanderLinden1** [comment]
Old issue which we do not need anymore
