### ISSUE TITLE
Ask Hannes about the "title split" & duplicate movies.

### ISSUE THREAD

**Issue by m-eren-erdogan** [course-dprep/team-project-team_8#7]
__Description__

During the merge of our datasetes, we've split the 'knownforTitles' column into 4 and merged 'title_1' with 'tconst'. We should ask about whether this process is correct or not.

In addition, we should also ask for removing the duplicate movies with unique() function.

_To be honest, I think these won't make crucial differences but asking Hannes about them is a +1 for the group so..._

__Deliverables__

Nothing to be honest.

**Comment by m-eren-erdogan** [comment]
# The answer: Do this again next week.

**Comment by KayvanderLinden1** [comment]
Asked in class --> Floris will pick this up in data cleaning
