### ISSUE TITLE
Play around with the dataset.

### ISSUE THREAD

**Issue by m-eren-erdogan** [course-dprep/team-project-team_8#9]
__Description__

You can find the dataset and the script following in the _dataset_ branch. You have to manually download the constituting parts from imdb.com such as _title.principal_ and vice versa. Feel free to filter, to aggregate, to compare and to come up with new ideas on how to develope it further.

__Deliverables__

Altered datasets if possible?

**Comment by KayvanderLinden1** [comment]
Everyone has done some testing with the dataset to get familiar. This issue can be closed.
